
package com.parabittechnology.parabit_newas;

import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mritunjay Singh
 */
public class Pbt_EnvNewApproval extends javax.swing.JDialog {
ParabitDB rec,table1,nextTable;
int stCode;
    /**
     * Creates new form Pbt_EnvNewApproval
     */
    public Pbt_EnvNewApproval(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public Pbt_EnvNewApproval(ParabitDB ob)
    {
        rec=ob;
        table1=new ParabitDB();
        nextTable= new ParabitDB();
        initComponents();
        additional();
       
        
    }
    private void additional()
    {
        try
        {
             stCode = rec.rs.getInt("STCode");
             tableUpdate(stCode);
        }catch(Exception e){System.out.println(e);}
    }
    private void tableUpdate(int e) throws Exception // Status E Entry Will Be Fetch and further Forward to Plant Plantation Officer
    {
        DefaultTableModel model1= (DefaultTableModel)jTableApproval.getModel();
        model1.setRowCount(0);
        String fetch = "Select * from landdata where STCode='"+e+"' and Status ='E'";
        PreparedStatement pst = table1.con.prepareStatement(fetch);
        table1.rs= pst.executeQuery();
        while(table1.rs.next())
        {
            int landId = table1.rs.getInt("Land_Id");
            String landType=table1.rs.getString("LandType");
            String soilType=table1.rs.getString("SoilType");
            String landPurpose=table1.rs.getString("LandPurpose");
            String areaSize= table1.rs.getString("AreaSize");
            model1.addRow(new Object[]{landId,landType,soilType,landPurpose,areaSize});
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableApproval = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTableApproval.setBackground(new java.awt.Color(204, 204, 204));
        jTableApproval.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableApproval.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableApproval.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LAND ID", "LAND TYPE", "SOIL TYPE", "LAND PURPOSE", "AREA SIZE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableApproval.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableApprovalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableApproval);
        if (jTableApproval.getColumnModel().getColumnCount() > 0) {
            jTableApproval.getColumnModel().getColumn(0).setResizable(false);
            jTableApproval.getColumnModel().getColumn(1).setResizable(false);
            jTableApproval.getColumnModel().getColumn(2).setResizable(false);
            jTableApproval.getColumnModel().getColumn(3).setResizable(false);
            jTableApproval.getColumnModel().getColumn(4).setResizable(false);
        }

        jComboBox1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTableApprovalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableApprovalMouseClicked
DefaultTableModel model1 = (DefaultTableModel)jTableApproval.getModel();

String landId = model1.getValueAt(jTableApproval.getSelectedRow(),0).toString();
try{
    String r = "Select * from landdata Where Land_Id ='"+landId+"'";
    PreparedStatement pst = nextTable.con.prepareStatement(r);
    nextTable.rs= pst.executeQuery();
    if(nextTable.rs.next())
    {
        PbtNN_ReportData obj = new PbtNN_ReportData(nextTable,true);
        Pbt_EnvReportDataForWard reportUpdate = new Pbt_EnvReportDataForWard(nextTable,rec);
        reportUpdate.setTitle(nextTable.rs.getString("LandPurpose")+"  Information Update");
        reportUpdate.setVisible(true);
        obj.setVisible(true);
    }
    
   
}catch(Exception re)
{
    System.out.println(re);
}
    }//GEN-LAST:event_jTableApprovalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pbt_EnvNewApproval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pbt_EnvNewApproval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pbt_EnvNewApproval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pbt_EnvNewApproval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pbt_EnvNewApproval dialog = new Pbt_EnvNewApproval(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableApproval;
    // End of variables declaration//GEN-END:variables
}
